services:
  - type: web
    name: kamrate-invoice-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn knlLogistics.wsgi --bind 0.0.0.0:10000
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.7
    databases:
      - name: postgresql
        plan: free